# Setup
title:        Nahuel site
tagline:      This site introduces my blog written about things that I am interested in.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Nahuel
  url:        

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
